name: Notify on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":" A branch was *merged* into `main` by ${{ github.actor }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
